def format_card_info(input_text):
    # Split the input text into lines and initialize variables
    lines = input_text.split('\n')
    results = []
    current_id = None
    current_name = None
    current_rarity = None

    # Process each line
    for line in lines:
        line = line.strip()
        if line.startswith('"id":'):
            # Save the previous card's info if available
            if current_id and current_name and current_rarity:
                results.append((current_id, current_name, current_rarity))
            # Extract the new ID and reset the name and rarity
            current_id = line.split('"')[3]
            current_name = None  # Reset name for the new card
            current_rarity = None  # Reset rarity for the new card
        elif line.startswith('"name":') and not current_name:
            # Extract the first name after the ID
            current_name = line.split('"')[3]
        elif line.startswith('"rarity":'):
            # Extract rarity, convert to lowercase and replace spaces with underscores
            current_rarity = line.split('"')[3].lower().replace(' ', '_')

    # Save the last card's info if not already saved
    if current_id and current_name and current_rarity:
        results.append((current_id, current_name, current_rarity))

    return results

# Input text
input_text = """
            "id": "swsh7-6",
      "name": "Tropius",
          "name": "Rally Back",
          "name": "Solar Beam",
      "id": "swsh7-9",
      "name": "Petilil",
          "name": "Seed Bomb",
      "id": "swsh7-13",
      "name": "Trevenant V",
          "name": "Absorb Life",
          "name": "Shadow Claw",
      "rarity": "Rare Holo V",
      "id": "swsh7-7",
      "name": "Leafeon V",
          "name": "Greening Cells",
          "name": "Leaf Blade",
      "rarity": "Rare Holo V",
      "id": "swsh7-32",
      "name": "Lotad",
          "name": "Call for Family",
          "name": "Rain Splash",
      "id": "swsh7-22",
      "name": "Litleo",
          "name": "Live Coal",
      "id": "swsh7-37",
      "name": "Feebas",
          "name": "Flail Around",
      "id": "swsh7-20",
      "name": "Victini",
          "name": "Victory Dive",
      "id": "swsh7-63",
      "name": "Galarian Articuno",
          "name": "Cruel Charge",
          "name": "Psylaser",
      "id": "swsh7-60",
      "name": "Regieleki",
          "name": "Static Shock",
          "name": "Teraspark",
      "id": "swsh7-67",
      "name": "Sableye",
          "name": "Go and Collect",
          "name": "Corner",
      "id": "swsh7-81",
      "name": "Hitmonchan",
          "name": "Clean Hit",
          "name": "Bullet Straight Punch",
      "id": "swsh7-94",
      "name": "Umbreon V",
          "name": "Mean Look",
          "name": "Moonlight Blade",
      "rarity": "Rare Holo V",
      "id": "swsh7-92",
      "name": "Lycanroc VMAX",
          "name": "Hunting Claw",
          "name": "Max Edge",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-96",
      "name": "Nuzleaf",
          "name": "Fake Out",
      "id": "swsh7-93",
      "name": "Galarian Moltres",
          "name": "Malevolent Charge",
          "name": "Fiery Wrath",
      "id": "swsh7-104",
      "name": "Nickit",
          "name": "Tail Whap",
      "id": "swsh7-107",
      "name": "Bagon",
          "name": "Gnaw",
          "name": "Headbutt",
      "id": "swsh7-109",
      "name": "Salamence",
          "name": "Intimidating Roar",
          "name": "Fierce Dragon",
      "id": "swsh7-113",
      "name": "Deino",
          "name": "Call for Family",
          "name": "Bite",
      "id": "swsh7-110",
      "name": "Rayquaza V",
          "name": "Dragon Pulse",
          "name": "Spiral Burst",
      "rarity": "Rare Holo V",
      "id": "swsh7-117",
      "name": "Noivern V",
          "name": "Boomburst",
          "name": "Synchro Loud",
      "rarity": "Rare Holo V",
      "id": "swsh7-114",
      "name": "Zweilous",
          "name": "Bite",
          "name": "Dragon Headbutt",
      "id": "swsh7-123",
      "name": "Duraludon VMAX",
          "name": "Skyscraper",
          "name": "G-Max Pulverization",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-128",
      "name": "Smeargle",
          "name": "Live Painting",
      "id": "swsh7-126",
      "name": "Teddiursa",
          "name": "Scratch",
      "id": "swsh7-131",
      "name": "Slaking",
          "name": "Act Freely",
          "name": "Rout",
      "id": "swsh7-138",
      "name": "Fletchling",
          "name": "Tailwind Draw",
          "name": "Surprise Attack",
      "id": "swsh7-149",
      "name": "Gordie",
      "id": "swsh7-164",
      "name": "Zinnia's Resolve",
      "id": "swsh7-161",
      "name": "Stormy Mountains",
      "id": "swsh7-163",
      "name": "Toy Catcher",
      "id": "swsh7-169",
      "name": "Flareon V",
          "name": "Flaming Breath",
          "name": "Scorching Column",
      "rarity": "Rare Ultra",
      "id": "swsh7-174",
      "name": "Glaceon V",
          "name": "Frozen Awakening",
          "name": "Heavy Snow",
      "rarity": "Rare Ultra",
      "id": "swsh7-185",
      "name": "Medicham V",
          "name": "Yoga Loop",
          "name": "Smash Uppercut",
      "rarity": "Rare Ultra",
      "id": "swsh7-187",
      "name": "Lycanroc V",
          "name": "Rock Throw",
          "name": "Crashing Fangs",
      "rarity": "Rare Ultra",
      "id": "swsh7-190",
      "name": "Garbodor V",
          "name": "Trash Stench",
          "name": "Sludge Bomb",
      "rarity": "Rare Ultra",
      "id": "swsh7-192",
      "name": "Dragonite V",
          "name": "Shred",
          "name": "Dragon Gale",
      "rarity": "Rare Ultra",
      "id": "swsh7-199",
      "name": "Aroma Lady",
      "rarity": "Rare Ultra",
      "id": "swsh7-200",
      "name": "Copycat",
      "rarity": "Rare Ultra",
      "id": "swsh7-4",
      "name": "Jumpluff",
          "name": "Fluffy Barrage",
          "name": "Spinning Attack",
      "id": "swsh7-1",
      "name": "Pinsir",
          "name": "Vise Coach",
          "name": "Seismic Toss",
      "id": "swsh7-11",
      "name": "Dwebble",
          "name": "Ram",
          "name": "Sharp Claws",
      "id": "swsh7-44",
      "name": "Bergmite",
          "name": "Tackle",
          "name": "Spinning Attack",
      "id": "swsh7-58",
      "name": "Dracozolt V",
          "name": "Primeval Beak",
          "name": "Mountain Swing",
      "rarity": "Rare Holo V",
      "id": "swsh7-30",
      "name": "Vaporeon VMAX",
          "name": "Bubble Pod",
          "name": "Max Torrent",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-47",
      "name": "Eiscue",
          "name": "Icy Snow",
          "name": "Blockface",
      "id": "swsh7-34",
      "name": "Ludicolo",
          "name": "Enthusiastic Dance",
          "name": "Wave Splash",
      "id": "swsh7-42",
      "name": "Tympole",
          "name": "Mud-Slap",
      "id": "swsh7-31",
      "name": "Suicune V",
          "name": "Fleet-Footed",
          "name": "Blizzard Rondo",
      "rarity": "Rare Holo V",
      "id": "swsh7-49",
      "name": "Pikachu",
          "name": "Energize",
          "name": "Electro Ball",
      "id": "swsh7-16",
      "name": "Eldegoss",
          "name": "Cotton Lift",
          "name": "Cotton Guard",
      "id": "swsh7-53",
      "name": "Lanturn",
          "name": "Blinding Beam",
          "name": "Electro Ball",
      "id": "swsh7-39",
      "name": "Luvdisc",
          "name": "Synchrodraw",
          "name": "Water Gun",
      "id": "swsh7-17",
      "name": "Applin",
          "name": "Rollout",
      "id": "swsh7-18",
      "name": "Flareon VMAX",
          "name": "Max Detonate",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-51",
      "name": "Jolteon VMAX",
          "name": "Max Thunder Rumble",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-57",
      "name": "Emolga",
          "name": "Thunder Shock",
      "id": "swsh7-55",
      "name": "Flaaffy",
          "name": "Dynamotor",
          "name": "Electro Ball",
      "id": "swsh7-61",
      "name": "Drowzee",
          "name": "Pound",
      "id": "swsh7-64",
      "name": "Espeon V",
          "name": "Zen Shot",
          "name": "Super Psy Bolt",
      "rarity": "Rare Holo V",
      "id": "swsh7-69",
      "name": "Swoobat",
          "name": "Synchro Woofer",
      "id": "swsh7-68",
      "name": "Woobat",
          "name": "Collect",
          "name": "Gnaw",
      "id": "swsh7-70",
      "name": "Golurk V",
          "name": "Mega Punch",
          "name": "Rewind Beam",
      "rarity": "Rare Holo V",
      "id": "swsh7-71",
      "name": "Flabébé",
          "name": "Hypnotic Gaze",
      "id": "swsh7-72",
      "name": "Floette",
          "name": "Fairy Wind",
          "name": "Double Spin",
      "id": "swsh7-80",
      "name": "Marshadow",
          "name": "Rapid Hunt",
          "name": "Shadow Flicker",
      "id": "swsh7-83",
      "name": "Medicham V",
          "name": "Yoga Loop",
          "name": "Smash Uppercut",
      "rarity": "Rare Holo V",
      "id": "swsh7-84",
      "name": "Hippopotas",
          "name": "Tackle",
          "name": "Mud Shot",
      "id": "swsh7-90",
      "name": "Seismitoad",
          "name": "Shaky Wave",
          "name": "Hyper Voice",
      "id": "swsh7-89",
      "name": "Palpitoad",
          "name": "Stampede",
          "name": "Tongue Slap",
      "id": "swsh7-98",
      "name": "Scraggy",
          "name": "Hard Head",
      "id": "swsh7-102",
      "name": "Zorua",
          "name": "Rear Kick",
      "id": "swsh7-100",
      "name": "Garbodor V",
          "name": "Trash Stench",
          "name": "Sludge Bomb",
      "rarity": "Rare Holo V",
      "id": "swsh7-112",
      "name": "Dialga",
          "name": "Chrono Wind",
          "name": "Heavy Impact",
      "id": "swsh7-115",
      "name": "Hydreigon",
          "name": "Dragon Counter",
          "name": "Pitch-Black Fangs",
      "id": "swsh7-124",
      "name": "Regidrago",
          "name": "Hammer In",
          "name": "Dragon Energy",
      "id": "swsh7-130",
      "name": "Vigoroth",
          "name": "Shatter",
          "name": "Slash",
      "id": "swsh7-127",
      "name": "Ursaring",
          "name": "Slash",
          "name": "Whap Down",
      "id": "swsh7-134",
      "name": "Herdier",
          "name": "Tackle",
          "name": "Take Down",
      "id": "swsh7-133",
      "name": "Lillipup",
          "name": "Lead",
          "name": "Tackle",
      "id": "swsh7-137",
      "name": "Braviary",
          "name": "Valiant Talons",
          "name": "Brave Bird",
      "id": "swsh7-135",
      "name": "Stoutland",
          "name": "Intimidating Fang",
          "name": "Knock Away",
      "id": "swsh7-141",
      "name": "Aroma Lady",
      "id": "swsh7-144",
      "name": "Crystal Cave",
      "id": "swsh7-142",
      "name": "Boost Shake",
      "id": "swsh7-147",
      "name": "Elemental Badge",
      "id": "swsh7-153",
      "name": "Rapid Strike Scroll of the Flying Dragon",
          "name": "Meteor",
      "id": "swsh7-162",
      "name": "Switching Cups",
      "id": "swsh7-166",
      "name": "Leafeon V",
          "name": "Greening Cells",
          "name": "Leaf Blade",
      "rarity": "Rare Ultra",
      "id": "swsh7-171",
      "name": "Gyarados V",
          "name": "Get Angry",
          "name": "Heavy Storm",
      "rarity": "Rare Ultra",
      "id": "swsh7-172",
      "name": "Vaporeon V",
          "name": "Triple Draw",
          "name": "Splash Jump",
      "rarity": "Rare Ultra",
      "id": "swsh7-180",
      "name": "Espeon V",
          "name": "Zen Shot",
          "name": "Super Psy Bolt",
      "rarity": "Rare Ultra",
      "id": "swsh7-189",
      "name": "Umbreon V",
          "name": "Mean Look",
          "name": "Moonlight Blade",
      "rarity": "Rare Ultra",
      "id": "swsh7-194",
      "name": "Rayquaza V",
          "name": "Dragon Pulse",
          "name": "Spiral Burst",
      "rarity": "Rare Ultra",
      "id": "swsh7-207",
      "name": "Gyarados VMAX",
          "name": "Hyper Beam",
          "name": "Max Tyrant",
      "rarity": "Rare Rainbow",
      "id": "swsh7-220",
      "name": "Duraludon VMAX",
          "name": "Skyscraper",
          "name": "G-Max Pulverization",
      "rarity": "Rare Rainbow",
      "id": "swsh7-229",
      "name": "Boost Shake",
      "rarity": "Rare Secret",
      "id": "swsh7-233",
      "name": "Toy Catcher",
      "rarity": "Rare Secret",
      "id": "swsh7-231",
      "name": "Full Face Guard",
      "rarity": "Rare Secret",
      "id": "swsh7-237",
      "name": "Metal Energy",
      "rarity": "Rare Secret",
      "id": "swsh7-2",
      "name": "Hoppip",
          "name": "Continuous Spin",
      "id": "swsh7-8",
      "name": "Leafeon VMAX",
          "name": "Grass Knot",
          "name": "Max Leaf",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-10",
      "name": "Lilligant",
          "name": "Dizzying Flower",
      "id": "swsh7-12",
      "name": "Crustle",
          "name": "X-Scissor",
          "name": "Hammer In",
      "id": "swsh7-14",
      "name": "Trevenant VMAX",
          "name": "Missing in the Forest",
          "name": "Max Tree",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-36",
      "name": "Sharpedo",
          "name": "Taunt",
          "name": "Jet Bite",
      "id": "swsh7-35",
      "name": "Carvanha",
          "name": "Ram",
          "name": "Razor Fin",
      "id": "swsh7-59",
      "name": "Dracozolt VMAX",
          "name": "Spark Trap",
          "name": "Max Impact",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-40",
      "name": "Glaceon V",
          "name": "Frozen Awakening",
          "name": "Heavy Snow",
      "rarity": "Rare Holo V",
      "id": "swsh7-24",
      "name": "Psyduck",
          "name": "Rain Splash",
      "id": "swsh7-26",
      "name": "Tentacool",
          "name": "Gentle Slap",
      "id": "swsh7-50",
      "name": "Raichu",
          "name": "Big Sparking",
          "name": "Thunderbolt",
      "id": "swsh7-19",
      "name": "Entei",
          "name": "Angry Fang",
          "name": "Heat Tackle",
      "id": "swsh7-29",
      "name": "Gyarados VMAX",
          "name": "Hyper Beam",
          "name": "Max Tyrant",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-52",
      "name": "Chinchou",
          "name": "Electro Ball",
      "id": "swsh7-45",
      "name": "Avalugg",
          "name": "Frost Barrier",
          "name": "Hammer In",
      "id": "swsh7-56",
      "name": "Ampharos",
          "name": "Thunder Shock",
          "name": "Electron Crush",
      "id": "swsh7-15",
      "name": "Gossifleur",
          "name": "Blot",
      "id": "swsh7-65",
      "name": "Espeon VMAX",
          "name": "Solar Revelation",
          "name": "Max Mindstorm",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-75",
      "name": "Sylveon VMAX",
          "name": "Precious Touch",
          "name": "Max Harmony",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-76",
      "name": "Pumpkaboo",
          "name": "Pumpkin Pit",
          "name": "Stampede",
      "id": "swsh7-77",
      "name": "Gourgeist",
          "name": "Pandemonium",
      "id": "swsh7-79",
      "name": "Ribombee",
          "name": "Tricky Steps",
      "id": "swsh7-85",
      "name": "Hippowdon",
          "name": "Hammer In",
          "name": "Sand Press",
      "id": "swsh7-82",
      "name": "Galarian Zapdos",
          "name": "Strong Legs Charge",
          "name": "Zapper Kick",
      "id": "swsh7-86",
      "name": "Roggenrola",
          "name": "Mud-Slap",
          "name": "Rolling Tackle",
      "id": "swsh7-87",
      "name": "Boldore",
          "name": "Protect",
          "name": "Boulder Crush",
      "id": "swsh7-91",
      "name": "Lycanroc V",
          "name": "Rock Throw",
          "name": "Crashing Fangs",
      "rarity": "Rare Holo V",
      "id": "swsh7-95",
      "name": "Umbreon VMAX",
          "name": "Dark Signal",
          "name": "Max Darkness",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-97",
      "name": "Shiftry",
          "name": "Shiftadieu",
          "name": "Nipping Cyclone",
      "id": "swsh7-101",
      "name": "Garbodor VMAX",
          "name": "Rubbish Collecting",
          "name": "G-Max Malodor",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-106",
      "name": "Altaria",
          "name": "Tempting Tune",
          "name": "Glide",
      "id": "swsh7-105",
      "name": "Thievul",
          "name": "Fumbling Hands",
          "name": "Tail Smack",
      "id": "swsh7-108",
      "name": "Shelgon",
          "name": "Hard Roll",
      "id": "swsh7-116",
      "name": "Kyurem",
          "name": "Extreme Freeze",
      "id": "swsh7-118",
      "name": "Zygarde",
          "name": "Bite",
          "name": "Judgment Surge",
      "id": "swsh7-120",
      "name": "Flapple",
          "name": "Acidic Mucus",
          "name": "Fighting Tackle",
      "id": "swsh7-121",
      "name": "Appletun",
          "name": "Thick Mucus",
          "name": "Fighting Tackle",
      "id": "swsh7-122",
      "name": "Duraludon V",
          "name": "Metal Claw",
          "name": "Breaking Swipe",
      "rarity": "Rare Holo V",
      "id": "swsh7-129",
      "name": "Slakoth",
          "name": "Smack 'n' Slack",
      "id": "swsh7-139",
      "name": "Fletchinder",
          "name": "Quick Attack",
      "id": "swsh7-140",
      "name": "Talonflame",
          "name": "Clutch",
          "name": "Nitro Dive",
      "id": "swsh7-143",
      "name": "Copycat",
      "id": "swsh7-151",
      "name": "Moon & Sun Badge",
      "id": "swsh7-160",
      "name": "Spirit Mask",
      "id": "swsh7-159",
      "name": "Snow Leaf Badge",
      "id": "swsh7-165",
      "name": "Treasure Energy",
      "id": "swsh7-170",
      "name": "Volcarona V",
          "name": "Surging Flames",
          "name": "Fire Blast",
      "rarity": "Rare Ultra",
      "id": "swsh7-175",
      "name": "Glaceon V",
          "name": "Frozen Awakening",
          "name": "Heavy Snow",
      "rarity": "Rare Ultra",
      "id": "swsh7-176",
      "name": "Arctovish V",
          "name": "Ancient Freeze",
          "name": "Giga Impact",
      "rarity": "Rare Ultra",
      "id": "swsh7-181",
      "name": "Golurk V",
          "name": "Mega Punch",
          "name": "Rewind Beam",
      "rarity": "Rare Ultra",
      "id": "swsh7-184",
      "name": "Sylveon V",
          "name": "Dream Gift",
          "name": "Magical Shot",
      "rarity": "Rare Ultra",
      "id": "swsh7-182",
      "name": "Golurk V",
          "name": "Mega Punch",
          "name": "Rewind Beam",
      "rarity": "Rare Ultra",
      "id": "swsh7-186",
      "name": "Medicham V",
          "name": "Yoga Loop",
          "name": "Smash Uppercut",
      "rarity": "Rare Ultra",
      "id": "swsh7-191",
      "name": "Dragonite V",
          "name": "Shred",
          "name": "Dragon Gale",
      "rarity": "Rare Ultra",
      "id": "swsh7-195",
      "name": "Noivern V",
          "name": "Boomburst",
          "name": "Synchro Loud",
      "rarity": "Rare Ultra",
      "id": "swsh7-196",
      "name": "Noivern V",
          "name": "Boomburst",
          "name": "Synchro Loud",
      "rarity": "Rare Ultra",
      "id": "swsh7-208",
      "name": "Glaceon VMAX",
          "name": "Crystal Veil",
          "name": "Max Icicle",
      "rarity": "Rare Rainbow",
      "id": "swsh7-209",
      "name": "Glaceon VMAX",
          "name": "Crystal Veil",
          "name": "Max Icicle",
      "rarity": "Rare Rainbow",
      "id": "swsh7-213",
      "name": "Lycanroc VMAX",
          "name": "Hunting Claw",
          "name": "Max Edge",
      "rarity": "Rare Rainbow",
      "id": "swsh7-215",
      "name": "Umbreon VMAX",
          "name": "Dark Signal",
          "name": "Max Darkness",
      "rarity": "Rare Rainbow",
      "id": "swsh7-217",
      "name": "Rayquaza VMAX",
          "name": "Azure Pulse",
          "name": "Max Burst",
      "rarity": "Rare Rainbow",
      "id": "swsh7-224",
      "name": "Raihan",
      "rarity": "Rare Rainbow",
      "id": "swsh7-226",
      "name": "Froslass",
          "name": "Frost Over",
          "name": "Crystal Breath",
      "rarity": "Rare Secret",
      "id": "swsh7-3",
      "name": "Skiploom",
          "name": "Solar Evolution",
          "name": "Spinning Attack",
      "id": "swsh7-5",
      "name": "Seedot",
          "name": "Astonish",
      "id": "swsh7-41",
      "name": "Glaceon VMAX",
          "name": "Crystal Veil",
          "name": "Max Icicle",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-46",
      "name": "Wishiwashi",
          "name": "Group Power",
          "name": "Schooling Shot",
      "id": "swsh7-43",
      "name": "Cryogonal",
          "name": "Element Chain",
          "name": "Icy Snow",
      "id": "swsh7-28",
      "name": "Gyarados V",
          "name": "Get Angry",
          "name": "Heavy Storm",
      "rarity": "Rare Holo V",
      "id": "swsh7-25",
      "name": "Golduck",
          "name": "Psybeam",
          "name": "Surf",
      "id": "swsh7-27",
      "name": "Tentacruel",
          "name": "Wave Splash",
          "name": "Poisonous Prison",
      "id": "swsh7-23",
      "name": "Pyroar",
          "name": "Combustion",
          "name": "Rip Claw",
      "id": "swsh7-54",
      "name": "Mareep",
          "name": "Rear Kick",
          "name": "Electro Ball",
      "id": "swsh7-38",
      "name": "Milotic",
          "name": "Dew Guard",
          "name": "Double Smash",
      "id": "swsh7-21",
      "name": "Volcarona V",
          "name": "Surging Flames",
          "name": "Fire Blast",
      "rarity": "Rare Holo V",
      "id": "swsh7-33",
      "name": "Lombre",
          "name": "Wave Splash",
      "id": "swsh7-48",
      "name": "Arctovish V",
          "name": "Ancient Freeze",
          "name": "Giga Impact",
      "rarity": "Rare Holo V",
      "id": "swsh7-62",
      "name": "Hypno",
          "name": "Hypnosis",
          "name": "Wake-Up Slap",
      "id": "swsh7-66",
      "name": "Wobbuffet",
          "name": "Mirror Pain",
          "name": "Headbutt Bounce",
      "id": "swsh7-73",
      "name": "Florges",
          "name": "Rapid Strike Connection",
          "name": "Wonder Shine",
      "id": "swsh7-74",
      "name": "Sylveon V",
          "name": "Dream Gift",
          "name": "Magical Shot",
      "rarity": "Rare Holo V",
      "id": "swsh7-78",
      "name": "Cutiefly",
          "name": "Flap",
      "id": "swsh7-88",
      "name": "Gigalith",
          "name": "Guard Press",
          "name": "Pressure Shot",
      "id": "swsh7-99",
      "name": "Scrafty",
          "name": "Headbutt",
          "name": "Shakedown",
      "id": "swsh7-103",
      "name": "Zoroark",
          "name": "Phantom Transformation",
          "name": "Night Daze",
      "id": "swsh7-111",
      "name": "Rayquaza VMAX",
          "name": "Azure Pulse",
          "name": "Max Burst",
      "rarity": "Rare Holo VMAX",
      "id": "swsh7-119",
      "name": "Drampa",
          "name": "Corkscrew Punch",
          "name": "Berserk",
      "id": "swsh7-125",
      "name": "Eevee",
          "name": "Vee-Search",
          "name": "Stampede",
      "id": "swsh7-132",
      "name": "Swablu",
          "name": "Surprise Attack",
      "id": "swsh7-136",
      "name": "Rufflet",
          "name": "Whirlwind",
      "id": "swsh7-145",
      "name": "Digging Gloves",
      "id": "swsh7-148",
      "name": "Full Face Guard",
      "id": "swsh7-146",
      "name": "Dream Ball",
      "id": "swsh7-150",
      "name": "Lucky Ice Pop",
      "id": "swsh7-156",
      "name": "Rubber Gloves",
      "id": "swsh7-154",
      "name": "Rescue Carrier",
      "id": "swsh7-152",
      "name": "Raihan",
      "id": "swsh7-155",
      "name": "Ribbon Badge",
      "id": "swsh7-157",
      "name": "Shopping Center",
      "id": "swsh7-158",
      "name": "Single Strike Scroll of the Fanged Dragon",
          "name": "Superstrong Slash",
      "id": "swsh7-167",
      "name": "Leafeon V",
          "name": "Greening Cells",
          "name": "Leaf Blade",
      "rarity": "Rare Ultra",
      "id": "swsh7-168",
      "name": "Trevenant V",
          "name": "Absorb Life",
          "name": "Shadow Claw",
      "rarity": "Rare Ultra",
      "id": "swsh7-173",
      "name": "Suicune V",
          "name": "Fleet-Footed",
          "name": "Blizzard Rondo",
      "rarity": "Rare Ultra",
      "id": "swsh7-178",
      "name": "Dracozolt V",
          "name": "Primeval Beak",
          "name": "Mountain Swing",
      "rarity": "Rare Ultra",
      "id": "swsh7-177",
      "name": "Jolteon V",
          "name": "Thunder Spear",
          "name": "Pin Missile",
      "rarity": "Rare Ultra",
      "id": "swsh7-179",
      "name": "Espeon V",
          "name": "Zen Shot",
          "name": "Super Psy Bolt",
      "rarity": "Rare Ultra",
      "id": "swsh7-183",
      "name": "Sylveon V",
          "name": "Dream Gift",
          "name": "Magical Shot",
      "rarity": "Rare Ultra",
      "id": "swsh7-188",
      "name": "Umbreon V",
          "name": "Mean Look",
          "name": "Moonlight Blade",
      "rarity": "Rare Ultra",
      "id": "swsh7-193",
      "name": "Rayquaza V",
          "name": "Dragon Pulse",
          "name": "Spiral Burst",
      "rarity": "Rare Ultra",
      "id": "swsh7-197",
      "name": "Duraludon V",
          "name": "Metal Claw",
          "name": "Breaking Swipe",
      "rarity": "Rare Ultra",
      "id": "swsh7-201",
      "name": "Gordie",
      "rarity": "Rare Ultra",
      "id": "swsh7-205",
      "name": "Leafeon VMAX",
          "name": "Grass Knot",
          "name": "Max Leaf",
      "rarity": "Rare Rainbow",
      "id": "swsh7-202",
      "name": "Raihan",
      "rarity": "Rare Ultra",
      "id": "swsh7-203",
      "name": "Zinnia's Resolve",
      "rarity": "Rare Ultra",
      "id": "swsh7-204",
      "name": "Leafeon VMAX",
          "name": "Grass Knot",
          "name": "Max Leaf",
      "rarity": "Rare Rainbow",
      "id": "swsh7-210",
      "name": "Dracozolt VMAX",
          "name": "Spark Trap",
          "name": "Max Impact",
      "rarity": "Rare Rainbow",
      "id": "swsh7-218",
      "name": "Rayquaza VMAX",
          "name": "Azure Pulse",
          "name": "Max Burst",
      "rarity": "Rare Rainbow",
      "id": "swsh7-221",
      "name": "Aroma Lady",
      "rarity": "Rare Rainbow",
      "id": "swsh7-225",
      "name": "Zinnia's Resolve",
      "rarity": "Rare Rainbow",
      "id": "swsh7-223",
      "name": "Gordie",
      "rarity": "Rare Rainbow",
      "id": "swsh7-228",
      "name": "Cresselia",
          "name": "Crescent Glow",
          "name": "Photon Laser",
      "rarity": "Rare Secret",
      "id": "swsh7-227",
      "name": "Inteleon",
          "name": "Quick Shooting",
          "name": "Waterfall",
      "rarity": "Rare Secret",
      "id": "swsh7-230",
      "name": "Crystal Cave",
      "rarity": "Rare Secret",
      "id": "swsh7-235",
      "name": "Lightning Energy",
      "rarity": "Rare Secret",
      "id": "swsh7-234",
      "name": "Turffield Stadium",
      "rarity": "Rare Secret",
      "id": "swsh7-236",
      "name": "Darkness Energy",
      "rarity": "Rare Secret",
      "id": "swsh7-198",
      "name": "Duraludon V",
          "name": "Metal Claw",
          "name": "Breaking Swipe",
      "rarity": "Rare Ultra",
      "id": "swsh7-206",
      "name": "Trevenant VMAX",
          "name": "Missing in the Forest",
          "name": "Max Tree",
      "rarity": "Rare Rainbow",
      "id": "swsh7-212",
      "name": "Sylveon VMAX",
          "name": "Precious Touch",
          "name": "Max Harmony",
      "rarity": "Rare Rainbow",
      "id": "swsh7-211",
      "name": "Sylveon VMAX",
          "name": "Precious Touch",
          "name": "Max Harmony",
      "rarity": "Rare Rainbow",
      "id": "swsh7-214",
      "name": "Umbreon VMAX",
          "name": "Dark Signal",
          "name": "Max Darkness",
      "rarity": "Rare Rainbow",
      "id": "swsh7-216",
      "name": "Garbodor VMAX",
          "name": "Rubbish Collecting",
          "name": "G-Max Malodor",
      "rarity": "Rare Rainbow",
      "id": "swsh7-219",
      "name": "Duraludon VMAX",
          "name": "Skyscraper",
          "name": "G-Max Pulverization",
      "rarity": "Rare Rainbow",
      "id": "swsh7-222",
      "name": "Copycat",
      "rarity": "Rare Rainbow",
      "id": "swsh7-232",
      "name": "Stormy Mountains",
      "rarity": "Rare Secret",

"""


# Get formatted output
output = format_card_info(input_text)

# Print the results in the desired format
for item in output:
   print(f"('{item[0]}', '{item[1]}', {item[2]}_probability),")